import "./globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { getLocale } from "next-intl/server";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const locale = await getLocale();
  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <Script
          id="theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `try{var s=localStorage.getItem('theme');var t=s? s : 'light';var root=document.documentElement;root.classList.remove('dark','light');if(t==='dark'){root.classList.add('dark');}else{root.classList.add('light');}root.style.colorScheme=t;}catch(e){}`,
          }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}